source 'http://rubygems.org'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'rails', '3.1.1'

gem 'errship3', :require => 'errship3', :path => '../../'
gem 'airbrake'
gem 'libv8', '~> 3.11.8'


gem 'sqlite3-ruby'
gem 'mongoid'
gem 'mongo_mapper'
gem 'bson_ext'
gem "twitter-bootstrap-rails"
gem "therubyracer"
gem "less-rails" #Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS
gem "twitter-bootstrap-rails"